# Generated by Django 5.2.3 on 2025-11-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_customerpurchase'),
        ('recommender', '0002_add_product_to_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_customers', to='crmapp.customer_details'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_products', to='crmapp.product'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.OneToOneField(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='crmapp.product'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_customers', to='crmapp.customer_details'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_products', to='crmapp.product'),
        ),
    ]
