# Generated by Django 5.2.3 on 2025-11-29 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_sentmessagelog'),
        ('recommender', '0003_alter_interaction_customer_alter_interaction_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HybridRankingDebug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('num_candidates', models.IntegerField(default=0)),
                ('debug_log', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details')),
            ],
            options={
                'db_table': 'hybrid_ranking_debug',
            },
        ),
    ]
