# Generated by Django 5.2.3 on 2025-11-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        # Commented out since 'address' field no longer exists in UserProfile
        # migrations.RemoveField(
        #     model_name='userprofile',
        #     name='address',
        # ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Admin'),
                    ('sales', 'Sales'),
                    ('technician', 'Technician'),
                    ('customer', 'Customer')
                ],
                max_length=20
            ),
        ),
    ]
